name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v6

      - name: Verify
        run: emcc -v

      - name: Build
      #  run: make -d
        run: ls && emcc Main.cpp -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2 -s SDL2_IMAGE_FORMATS=["png"] -s ALLOW_MEMORY_GROWTH=1 --no-heap-copy --preload-file Fonts --shell-file shell_minimal.html -o index.html